version: '2'
services:
  web:
    build: .
    container_name: 'phoenix-app'
    ports:
      - "4000:4000"
    volumes:
    - ./:/myapp
    links:
     - mysql
    tty: true
  mysql:
    image: mysql
    container_name: 'mysql-phoenix-app'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root